services:
    dma-resources-server:
        image: ghcr.io/dnd-mapp/dma-resources-server
        container_name: dma-resources-server
        restart: unless-stopped
        ports:
            - "3000:3000"
        env_file:
            - ./.env
