name: Push to main branch
on:
    push:
        branches:
            - main
permissions:
    contents: read
    packages: write
env:
    E2E_SETUP: full
    MARIADB_HOST: localhost
    MARIADB_PORT: 3306
    MARIADB_SCHEMA: dma_e2e_resources_db
    MARIADB_USERNAME: dma_e2e_resources_db_user
    MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
jobs:
    ci:
        name: CI
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: CI
              uses: ./.github/actions/ci
    docker-build:
        name: Build and push Docker image
        needs: ci
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Build and push Docker image
              uses: ./.github/actions/docker-build
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
    e2e:
        name: E2E testing
        needs:
            - docker-build
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  cache: npm
                  node-version-file: .tool-versions
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Prepare MariaDB database root user password
              run: |
                  echo -n "${{ secrets.MARIADB_ROOT_PASSWORD }}" > e2e/root-password.txt
                  echo """
                      MARIADB_HOST="${{ env.MARIADB_HOST }}"
                      MARIADB_PORT="${{ env.MARIADB_PORT }}"
                      MARIADB_SCHEMA="${{ env.MARIADB_SCHEMA }}"
                      MARIADB_USERNAME="${{ env.MARIADB_USERNAME }}"
                      MARIADB_PASSWORD="${{ env.MARIADB_PASSWORD }}"
                      MARIADB_URL="mysql://${MARIADB_USERNAME}:${MARIADB_PASSWORD}@${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_SCHEMA}"
                  """ > .env

            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Run E2E tests
              run: npm run e2e:ci
